version: '3.7'
services:
  api:
    container_name: auth-api
    build:
      context: .
      args:
        MODE: production
    environment:
      NODE_ENV: production
    volumes:
      - .:/usr/src/app
    ports:
      - ${SERVER_PORT}:3000
    restart: always
    command: npm run start:prod
    networks:
      - auth-net

networks:
  auth-net:
    external: true
