version: '3.2'
services:
  db:
    container_name: ${SERVICE_NAME}-db
    image: postgres
    restart: always
    volumes:
      - 'postgres-data:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${PORT_DB_EXPOSE}:5432
    networks:
      - space-net

  db-test:
    container_name: ${SERVICE_NAME}-db-test
    image: postgres
    restart: always
    volumes:
      - 'postgres-data-test:/var/lib/postgresql/data'
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: ${DB_NAME}-test
    ports:
      - 5554:5432
    networks:
      - space-net

  api:
    container_name: ${SERVICE_NAME}-api
    build:
      context: .
      args:
        MODE: development
        PORT: ${PORT_API_EXPOSE}
    restart: always
    environment:
      NODE_ENV: development
    command: npm run start:dev
    ports:
      - ${PORT_API_EXPOSE}:3000
    volumes:
      - .:/usr/src/app
    depends_on:
      - 'db'
    networks:
      - space-net
      - auth-net

networks:
  space-net:
    external: true
  auth-net:
    external: true

volumes:
  postgres-data:
  postgres-data-test:
